service: theliturgists-backend-${self:custom.namespace}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    SLS_STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:DescribeParameters
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - "parameter/${self:custom.stage}/*"

functions:
  app:
    handler: index.handler
    timeout: 30
    events:
      - http: GET /patreon/authorize
      - http: POST /patreon/validate
      - http: GET /contentful/{proxy+}
  sync:
    handler: src/sync.handler
    timeout: 300
    events:
      - schedule:
          rate: cron(0 12 * * ? *)   # daily, 8AM EDT
          enabled: ${self:custom.syncEnabled.${self:custom.stage}}

custom:
  namespace: ${env:SLS_NAMESPACE, env:USER}
  stage: ${opt:stage, self:provider.stage}
  syncEnabled:
    dev: false
    staging: true
