service: theliturgists-backend

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    SLS_STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:DescribeParameters
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - "parameter/${self:custom.stage}/*"

functions:
  app:
    handler: index.handler
    timeout: 30
    events:
      - http: GET /patreon/authorize
      - http: POST /patreon/validate
      - http: GET /contentful/{proxy+}

custom:
  stage: ${opt:stage, self:provider.stage}
